### ISSUE TITLE
x64 Bit

### ISSUE THREAD

**Issue by Iydah** [Metastruct/gmsv_luapack_internal#10]
I beg you compile x64 bit versions of you're DLL's

**Comment by danielga** [comment]
As I mentioned on [#70](https://github.com/danielga/gmsv_serversecure/issues/70) and [#59](https://github.com/danielga/gmsv_serversecure/issues/59), there's no official support for that branch. If you're feeling brave, you can follow the [instructions here](https://github.com/danielga/gmsv_serversecure/issues/70#issuecomment-914529144) to compile the module yourself for x86-64.
