### ISSUE TITLE
whitelist bsp extension

### ISSUE THREAD

**Issue by Yogpod** [Metastruct/gmsv_luapack_internal#11]
add bsp to the extension whitelist for luapack.Rename
(then subsequently in the luapack addon change `"luapack/" .. luapack.CurrentHash .. ".dat"` to `"luapack/" .. luapack.CurrentHash .. ".bsp"`)
this lets people with `cl_downloadfilter mapsonly` to actually download the content instead of crashing

**Comment by danielga** [comment]
[Latest release](https://github.com/danielga/gmsv_luapack_internal/releases/tag/1.0.3) should allow `.bsp` extensions.

**Comment by Yogpod** [comment]
could also compress it with `bz2` i believe if it's bsp, is the bsp change planned for the develop branch of luapack?
