### ISSUE TITLE
AddOrUpdateFile new signature 

### ISSUE THREAD

**Issue by michak89** [Metastruct/gmsv_luapack_internal#6]
Hello

Last gmod update broke luapack, could You update this signature? 
:1st_place_medal:

**Comment by danielga** [comment]
Which operating system are you having this issue on? Is it on SRCDS?

**Comment by michak89** [comment]
Hello, tested on windows, yes srcds

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Wolny
od wirusów. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

sob., 13 lip 2019 o 19:20 Daniel <notifications@github.com> napisał(a):

**Comment by danielga** [comment]
I see, the problem isn't on the code but when the release was made, 2 more commits have been done since then. [Updated the release.](https://github.com/danielga/gmsv_luapack_internal/releases/tag/downloadables)
