### ISSUE TITLE
Can't use the module

### ISSUE THREAD

**Issue by DBotThePony** [Metastruct/gmsv_luapack_internal#7]
I've compiled it by myself for Linux and can't get it to work.

I tried to compile it for 32-bit target with `master` branch garrysmod_common and on startup server throw an error `failed to hook GModDataPack::AddOrUpdateFile` (on `stable` gmod branch of course)

Then i tried to compile it for 64-bit target with `x86-64-support-sourcesdk` branch on garrysmod_common and it fails on compilation:
![putty_kscsV7ePSW](https://user-images.githubusercontent.com/6339511/90335191-3a890680-dffd-11ea-9f27-08e37039a56b.png)

Removing last `true` argument from call make it compile, but on server startup when it need to load the module it instantly segaults.

**Comment by michak89** [comment]
I had same problem like a year ago, function signature is outdated again.
Last time author updated it but the code doesn't work anyway. It compiled
successfully but after implementation lua sending was broken - player could
not receive default lua files from send.txt.

**Comment by danielga** [comment]
Can you try [these builds](https://github.com/danielga/gmsv_luapack_internal/releases/tag/1.0.0) please?

**Comment by michak89** [comment]
Those are clean server files, downloaded today, windows:
gmsv_luapack_internal_win32.dll build from above. 
gmsv_crypt_win32.dll - old but should work propertly. 
Luapack code is up to date. 
Stock send.txt file renamed to _send.txt
Stock lua/includes/init,lua renamed to _init.lua
Luapack folder located in lua folder. 
Init.lua located in lua/includes.

Looks like .dll does work but can't get it running, little video here, 1 minute:
 (something interesting will happen with init.lua)
https://youtu.be/pqI2RzK813E

Error screenshot here:
![image](https://user-images.githubusercontent.com/40716529/90407374-bee39400-e0a6-11ea-8f81-a66dfb938b40.png)

:cactus:

**Comment by danielga** [comment]
By luapack folder, do you mean [this](https://github.com/danielga/luapack/)? Because that is meant to go into addons. Otherwise, I'm unable to reproduce the issue.

**Comment by michak89** [comment]
I just commented this few hours ago: 

--[[
if file.Exists("lua/includes/init.lua", "MOD") and not luapack.Rename("includes/init.lua", "includes/_init.lua", "MOD") then
	luapack.DebugMsg("Failed to rename init.lua to _init.lua (maybe 'lua/includes/_init.lua' already exists?)")
end

if file.Exists("lua/send.txt", "MOD") and not luapack.Rename("send.txt", "_send.txt", "MOD") then
	luapack.DebugMsg("Failed to rename send.txt to _send.txt (maybe 'lua/_send.txt' already exists?)")
end
--]]
its a bit modified, I tried few things. Anyway, now it works:
![image](https://user-images.githubusercontent.com/40716529/90435399-3b8a6880-e0cf-11ea-9799-564728faed8f.png)
Pack is successfully sent to player and found by clientside lua. 

But like a year ago it still fails to mount files on client and whole init fails.
I'm working on it right now, already found out how the pack is generated and read by clientside lua.
Code is definetly broken somehow, just try to use it Yourself   :cactus: 
(I mean luapack, not internal module)

Edit: I put the code into addons folder as You said, same issues.

**Comment by michak89** [comment]
Server: 
![image](https://user-images.githubusercontent.com/40716529/90437786-36c7b380-e0d3-11ea-9053-272dd7801889.png)


Client:
![image](https://user-images.githubusercontent.com/40716529/90437808-3fb88500-e0d3-11ea-9deb-46e62ba36c60.png)
Pack successfully downloaded.

Broken init:
![image](https://user-images.githubusercontent.com/40716529/90437955-8908d480-e0d3-11ea-936b-34cb3b55fe9b.png)
![image](https://user-images.githubusercontent.com/40716529/90437969-8dcd8880-e0d3-11ea-8aa1-8197aea23cb8.png)

:cactus:

**Comment by danielga** [comment]
This is a different problem altogether, unrelated to the module. Please use the [issues section of the addon](https://github.com/danielga/luapack/issues). I'm assuming that the module is working, given the screenshots.
